project_id = "rdccmplhvlwmkjrcayvc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.ai-summarize]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-suggest-notes]
verify_jwt = false

[functions.paddle-webhook]
verify_jwt = false

[functions.create-paddle-checkout]
verify_jwt = false

[functions.manage-subscription]
verify_jwt = false
